/* Generated By:JavaCC: Do not edit this line. calConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface calConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int ADD_OP = 7;
  /** RegularExpression Id. */
  int MULT_OP = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"(\"",
    "\")\"",
    "<ADD_OP>",
    "<MULT_OP>",
    "<NUMBER>",
  };

}
